### ISSUE TITLE
WHMCS versi 8.8 

### ISSUE THREAD

**Issue by myhardez** [veritrans/SNAP-whmcs#20]
mohon bantuan support 
saya menggunakan WHMCS versi 8.8 ada error response
modules/gateways/callback/veritrans.php

di dashboard midrans ada error

Today, 12:49 pm | Failed | < POST https://webku.com/modules/gateways/callback/veritrans.php > InternalServerError InternalServerError | pending

---------------------
ERROR DI WHMCS

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

If the problem persists, please contact us.

« Back to Homepage

For additional assistance, please reference the WHMCS TroubleShooting Guide »

Exception: Veritrans Error (): in /home/webku/public_html/modules/gateways/veritrans-lib/Veritrans/ApiRequestor.php:106
Stack trace:
#0 /home/webku/public_html/modules/gateways/veritrans-lib/Veritrans/ApiRequestor.php(17): Veritrans_ApiRequestor::remoteCall()
#1 /home/webku/public_html/modules/gateways/veritrans-lib/Veritrans/Transaction.php(17): Veritrans_ApiRequestor::get()
#2 /home/webku/public_html/modules/gateways/veritrans-lib/Veritrans/Notification.php(20): Veritrans_Transaction::status()
#3 /home/webku/public_html/modules/gateways/callback/veritrans.php(45): Veritrans_Notification->__construct()
#4 {main}

**Comment by myhardez** [comment]
Mohon maaf ini modul WHMCS MIDTRANS masih di SUPPORT atau tidak ya?
karena beberapa kali saya tanya SUPPORT tidak ada penyelesaian

terima kasih

**Comment by bencoverts** [comment]
Module nya kayaknya emang gak bisa di pake mas, Soalnya saya tadi Coba tes pembayaran Malah error Dan Produk Tidak Terbuat Otomatis Pada Saat Pembayaran Berhasil

Muncul Error 

```
Midtrans payment module encountered unexpected error when requesting to Snap API. Error message:Midtrans Error (400): {"error_messages":["transaction_details.order_id has already been taken"]} | Request url: https://app.midtrans.com/snap/v1/transactions
```

**Comment by myhardez** [comment]
Saya udah GK pakai midtrans lagi. Soalnya gk niat supportnya
